return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  enable = true,
  config = function()
    require("transparent").setup({ -- Optional, you don't have to run setup.
      groups = { -- table: default groups
        "Normal",
        "NormalNC",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "SignColumn",
        "CursorLineNr",
        "EndOfBuffer",
      },
      extra_groups = {
        "NormalFloat",
        "NvimTreeNormal",
        "VertSplit",
        "StatusLineNC",
        "SignColumn",
        "GitSignsAdd",
        "GitSignsChange",
        "GitSignsDelete",
        -- "ZenMode",
      },
      exclude_groups = {}, -- table: groups you don't want to clear
      on_clear = function() end,
    })
  end,
}
